// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     schema2.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// Sample schema to help you get started.
type Msg2 struct {
	// The id of the order.
	OrderId int32 `json:"orderId"`
}

const Msg2AvroCRC64Fingerprint = "\"\x0e\x93\x94\x19\x11\v\x9c"

func NewMsg2() Msg2 {
	r := Msg2{}
	return r
}

func DeserializeMsg2(r io.Reader) (Msg2, error) {
	t := NewMsg2()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeMsg2FromSchema(r io.Reader, schema string) (Msg2, error) {
	t := NewMsg2()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeMsg2(r Msg2, w io.Writer) error {
	var err error
	err = vm.WriteInt(r.OrderId, w)
	if err != nil {
		return err
	}
	return err
}

func (r Msg2) Serialize(w io.Writer) error {
	return writeMsg2(r, w)
}

func (r Msg2) Schema() string {
	return "{\"doc\":\"Sample schema to help you get started.\",\"fields\":[{\"doc\":\"The id of the order.\",\"name\":\"orderId\",\"type\":\"int\"}],\"name\":\"com.mycorp.mynamespace.Msg2\",\"type\":\"record\"}"
}

func (r Msg2) SchemaName() string {
	return "com.mycorp.mynamespace.Msg2"
}

func (_ Msg2) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Msg2) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Msg2) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Msg2) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Msg2) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Msg2) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Msg2) SetString(v string)   { panic("Unsupported operation") }
func (_ Msg2) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Msg2) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Int{Target: &r.OrderId}

		return w

	}
	panic("Unknown field index")
}

func (r *Msg2) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Msg2) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Msg2) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Msg2) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Msg2) HintSize(int)                     { panic("Unsupported operation") }
func (_ Msg2) Finalize()                        {}

func (_ Msg2) AvroCRC64Fingerprint() []byte {
	return []byte(Msg2AvroCRC64Fingerprint)
}

func (r Msg2) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["orderId"], err = json.Marshal(r.OrderId)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Msg2) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["orderId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.OrderId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for orderId")
	}
	return nil
}
